import { Shelter, User } from "@/types";

export const fakeUser: User[] = [
  {
    id: "1",
    firstName: "Juan",
    lastName: "Dela Cruz",
    middleName: "A.",
    email: "juan.delacruz@example.com",
    phoneNumber: "+639171234567",
    gender: "Male",
    dateOfBirth: "1990-04-12",
    age: 34,
    address: "123 Mabini Street, Manila",
    picture: "https://example.com/images/juan_delacruz.jpg",
  },
  {
    id: "2",
    firstName: "Maria",
    lastName: "Santos",
    middleName: "B.",
    email: "maria.santos@example.com",
    phoneNumber: "+639172345678",
    gender: "Female",
    dateOfBirth: "1992-07-05",
    age: 32,
    address: "456 Rizal Avenue, Quezon City",
    picture: "https://example.com/images/maria_santos.jpg",
  },
  {
    id: "3",
    firstName: "Pedro",
    lastName: "Reyes",
    middleName: "C.",
    email: "pedro.reyes@example.com",
    phoneNumber: "+639173456789",
    gender: "Male",
    dateOfBirth: "1988-11-19",
    age: 36,
    address: "789 Aguinaldo Street, Cebu City",
    picture: "https://example.com/images/pedro_reyes.jpg",
  },
  {
    id: "4",
    firstName: "Ana",
    lastName: "Garcia",
    middleName: "D.",
    email: "ana.garcia@example.com",
    phoneNumber: "+639184567890",
    gender: "Female",
    dateOfBirth: "1995-02-14",
    age: 29,
    address: "1010 Bonifacio Road, Davao City",
    picture: "https://example.com/images/ana_garcia.jpg",
  },
  {
    id: "5",
    firstName: "Carlos",
    lastName: "Morales",
    middleName: "E.",
    email: "carlos.morales@example.com",
    phoneNumber: "+639195678901",
    gender: "Male",
    dateOfBirth: "1985-09-23",
    age: 39,
    address: "1412 Luna Avenue, Bacolod City",
    picture: "https://example.com/images/carlos_morales.jpg",
  },
  {
    id: "6",
    firstName: "Lucia",
    lastName: "Gomez",
    middleName: "F.",
    email: "lucia.gomez@example.com",
    phoneNumber: "+639106789012",
    gender: "Female",
    dateOfBirth: "1993-06-11",
    age: 31,
    address: "2021 Del Pilar Street, Iloilo City",
    picture: "https://example.com/images/lucia_gomez.jpg",
  },
  {
    id: "7",
    firstName: "Jose",
    lastName: "Fernandez",
    middleName: "G.",
    email: "jose.fernandez@example.com",
    phoneNumber: "+639117890123",
    gender: "Male",
    dateOfBirth: "1991-03-29",
    age: 33,
    address: "3032 Rizal Street, Cagayan de Oro",
    picture: "https://example.com/images/jose_fernandez.jpg",
  },
  {
    id: "8",
    firstName: "Isabel",
    lastName: "Torres",
    middleName: "H.",
    email: "isabel.torres@example.com",
    phoneNumber: "+639128901234",
    gender: "Female",
    dateOfBirth: "1989-08-08",
    age: 35,
    address: "4043 Mabuhay Road, Zamboanga City",
    picture: "https://example.com/images/isabel_torres.jpg",
  },
  {
    id: "9",
    firstName: "Ramon",
    lastName: "Villanueva",
    middleName: "I.",
    email: "ramon.villanueva@example.com",
    phoneNumber: "+639139012345",
    gender: "Male",
    dateOfBirth: "1987-01-05",
    age: 37,
    address: "5054 Andres Street, Baguio City",
    picture: "https://example.com/images/ramon_villanueva.jpg",
  },
  {
    id: "10",
    firstName: "Cecilia",
    lastName: "Lopez",
    middleName: "J.",
    email: "cecilia.lopez@example.com",
    phoneNumber: "+639140123456",
    gender: "Female",
    dateOfBirth: "1994-10-10",
    age: 30,
    address: "6065 Luna Street, Tagaytay City",
    picture: "https://example.com/images/cecilia_lopez.jpg",
  },
  {
    id: "11",
    firstName: "Miguel",
    lastName: "Rosales",
    middleName: "K.",
    email: "miguel.rosales@example.com",
    phoneNumber: "+639151234567",
    gender: "Male",
    dateOfBirth: "1996-12-22",
    age: 27,
    address: "7076 Bonifacio Avenue, General Santos City",
    picture: "https://example.com/images/miguel_rosales.jpg",
  },
  {
    id: "12",
    firstName: "Rosa",
    lastName: "Castro",
    middleName: "L.",
    email: "rosa.castro@example.com",
    phoneNumber: "+639162345678",
    gender: "Female",
    dateOfBirth: "1990-05-18",
    age: 34,
    address: "8087 Mabini Street, Puerto Princesa",
    picture: "https://example.com/images/rosa_castro.jpg",
  },
  {
    id: "13",
    firstName: "Diego",
    lastName: "Mendoza",
    middleName: "M.",
    email: "diego.mendoza@example.com",
    phoneNumber: "+639173456789",
    gender: "Male",
    dateOfBirth: "1985-08-01",
    age: 39,
    address: "9098 Rizal Road, Dumaguete City",
    picture: "https://example.com/images/diego_mendoza.jpg",
  },
  {
    id: "14",
    firstName: "Lourdes",
    lastName: "Rivera",
    middleName: "N.",
    email: "lourdes.rivera@example.com",
    phoneNumber: "+639184567890",
    gender: "Female",
    dateOfBirth: "1991-12-25",
    age: 33,
    address: "10109 Aguinaldo Street, Naga City",
    picture: "https://example.com/images/lourdes_rivera.jpg",
  },
  {
    id: "15",
    firstName: "Andres",
    lastName: "Cruz",
    middleName: "O.",
    email: "andres.cruz@example.com",
    phoneNumber: "+639195678901",
    gender: "Male",
    dateOfBirth: "1987-11-15",
    age: 36,
    address: "11110 Magallanes Street, San Fernando",
    picture: "https://example.com/images/andres_cruz.jpg",
  },
  {
    id: "16",
    firstName: "Carmen",
    lastName: "Diaz",
    middleName: "P.",
    email: "carmen.diaz@example.com",
    phoneNumber: "+639106789012",
    gender: "Female",
    dateOfBirth: "1989-03-10",
    age: 35,
    address: "12121 Bonifacio Avenue, Tagbilaran City",
    picture: "https://example.com/images/carmen_diaz.jpg",
  },
  {
    id: "17",
    firstName: "Emilio",
    lastName: "Ramos",
    middleName: "Q.",
    email: "emilio.ramos@example.com",
    phoneNumber: "+639117890123",
    gender: "Male",
    dateOfBirth: "1993-07-07",
    age: 31,
    address: "13132 Mabuhay Road, Vigan City",
    picture: "https://example.com/images/emilio_ramos.jpg",
  },
  {
    id: "18",
    firstName: "Sofia",
    lastName: "Flores",
    middleName: "R.",
    email: "sofia.flores@example.com",
    phoneNumber: "+639128901234",
    gender: "Female",
    dateOfBirth: "1988-04-20",
    age: 36,
    address: "14143 Rizal Street, Laoag City",
    picture: "https://example.com/images/sofia_flores.jpg",
  },
  {
    id: "19",
    firstName: "Arturo",
    lastName: "Gonzalez",
    middleName: "S.",
    email: "arturo.gonzalez@example.com",
    phoneNumber: "+639139012345",
    gender: "Male",
    dateOfBirth: "1986-06-15",
    age: 38,
    address: "15154 Aguinaldo Avenue, Legazpi City",
    picture: "https://example.com/images/arturo_gonzalez.jpg",
  },
  {
    id: "20",
    firstName: "Victoria",
    lastName: "Martinez",
    middleName: "T.",
    email: "victoria.martinez@example.com",
    phoneNumber: "+639140123456",
    gender: "Female",
    dateOfBirth: "1997-09-30",
    age: 27,
    address: "16165 Luna Street, Tarlac City",
    picture: "https://example.com/images/victoria_martinez.jpg",
  },
];

export const fakeShelters: Shelter[] = [
  {
    id: "1",
    name: "Safe Haven Shelter",
    location: "Makati City",
    type: "Permanent",
    capacity: 8,
    status: "Available",
  },
  {
    id: "2",
    name: "Hope Refuge Center",
    location: "Quezon City",
    type: "Temporary",
    capacity: 5,
    status: "Occupied",
  },
  {
    id: "3",
    name: "Shelter of Light",
    location: "Pasig City",
    type: "Permanent",
    capacity: 7,
    status: "Full",
  },
  {
    id: "4",
    name: "Peaceful Nest",
    location: "Taguig City",
    type: "Temporary",
    capacity: 6,
    status: "Reserved",
  },
  {
    id: "5",
    name: "Sunrise Sanctuary",
    location: "Manila City",
    type: "Permanent",
    capacity: 8,
    status: "Available",
  },
  {
    id: "6",
    name: "Comfort Corner",
    location: "Mandaluyong City",
    type: "Temporary",
    capacity: 4,
    status: "Occupied",
  },
  {
    id: "7",
    name: "Rainbow Shelter",
    location: "Parañaque City",
    type: "Permanent",
    capacity: 6,
    status: "Full",
  },
  {
    id: "8",
    name: "Care Refuge",
    location: "Pasay City",
    type: "Temporary",
    capacity: 3,
    status: "Maintenance",
  },
  {
    id: "9",
    name: "Harbor Haven",
    location: "Caloocan City",
    type: "Permanent",
    capacity: 5,
    status: "Reserved",
  },
  {
    id: "10",
    name: "Unity Shelter",
    location: "Las Piñas City",
    type: "Temporary",
    capacity: 7,
    status: "Available",
  },
  {
    id: "11",
    name: "Serenity Refuge",
    location: "Muntinlupa City",
    type: "Permanent",
    capacity: 8,
    status: "Occupied",
  },
  {
    id: "12",
    name: "Blessing Shelter",
    location: "San Juan City",
    type: "Temporary",
    capacity: 2,
    status: "Full",
  },
  {
    id: "13",
    name: "Hope Harbor",
    location: "Valenzuela City",
    type: "Permanent",
    capacity: 4,
    status: "Reserved",
  },
  {
    id: "14",
    name: "New Beginnings",
    location: "Malabon City",
    type: "Temporary",
    capacity: 6,
    status: "Available",
  },
  {
    id: "15",
    name: "Sunset Shelter",
    location: "Navotas City",
    type: "Permanent",
    capacity: 8,
    status: "Occupied",
  },
  {
    id: "16",
    name: "Shelter of Peace",
    location: "Makati City",
    type: "Temporary",
    capacity: 5,
    status: "Maintenance",
  },
  {
    id: "17",
    name: "Tranquil Harbor",
    location: "Quezon City",
    type: "Permanent",
    capacity: 7,
    status: "Full",
  },
  {
    id: "18",
    name: "Haven of Hope",
    location: "Pasig City",
    type: "Temporary",
    capacity: 6,
    status: "Reserved",
  },
  {
    id: "19",
    name: "Careful Shelter",
    location: "Taguig City",
    type: "Permanent",
    capacity: 8,
    status: "Available",
  },
  {
    id: "20",
    name: "Blessed Refuge",
    location: "Mandaluyong City",
    type: "Temporary",
    capacity: 4,
    status: "Occupied",
  },
];
